### PR TITLE
Bump default poetry to 1.2.2

### PR DESCRIPTION
**Pull request by arichtman**

### CODE REVIEW

**Comment by Apakottur** [comment]
Thanks for the PR!
Can you please also change the default poetry version in the README, so that it's up to date?

We can then merge this :)

**Comment by arichtman** [comment]
Done (:

**Comment by Apakottur** [comment]
Cool!

I see now that CI is failing. Can you try merging the most recent `main` into your branch and pushing again?
I think it should work then.

**Review by Apakottur — APPROVED** [review]
Nice, looks good!

**Pull request merged**
